name = "Rat's Mischief ğŸ€"
filename = "ratsmischief-1.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3521/750/ratsmischief-1.3.1.jar"
hash-format = "murmur2"
hash = "2746261046"

[update]
[update.curseforge]
file-id = 3521750
project-id = 431787
release-channel = "beta"
