name = "Rat's Mischief ğŸ€"
filename = "ratsmischief-1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3519/134/ratsmischief-1.3.jar"
hash-format = "murmur2"
hash = "2288139821"

[update]
[update.curseforge]
file-id = 3519134
project-id = 431787
release-channel = "beta"
