name = "Rat's Mischief ğŸ€"
filename = "ratsmischief-1.2.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3493/949/ratsmischief-1.2.3.jar"
hash-format = "murmur2"
hash = "2904248694"

[update]
[update.curseforge]
file-id = 3493949
project-id = 431787
release-channel = "beta"
